Increment8
iRootPro/shortURL pull request #8
Opened 2022-10-21 13:58 UTC by iRootPro

2022-10-24 13:55 UTC, Perederey requested changes
В целом хорошая работа, но есть три критичных момента
1) Открывать каждый раз при записи/чтении не правильно, нужно открывать файл только один раз.
2) Переделать парсинг флагов, чтобы избавитсья от танцев с указателями
3) Передавать в хедлер storage (repo) нужно зависимостью, иначе код разрастется и будет не читабельным.

2022-10-24 13:55 UTC, Perederey commented on internal/url/handlers/handlers.go
> +	}
выглядит немноно странно, много повторяющегося кода. это так echo просит вставлять зависимости? 
Может быть попробуем переписать на chi?

2022-10-24 13:55 UTC, Perederey commented on internal/url/handlers/handlers.go
> +
лишняя пустая строка

2022-10-24 13:55 UTC, Perederey commented on internal/url/handlers/handlers.go
> +	}
в go не очень любят else, подумай как можно избавится от else в этом месте?
Можно ли как-то зависимостью передать storager, как интрефейс, где твой-бы хендлер не беспоколился о логике хранилища?

2022-10-24 13:55 UTC, Perederey commented on internal/url/handlers/handlers.go
> +	}
и ты бы вызывал бы только один метод `storage.Put(link)`

2022-10-24 13:55 UTC, Perederey commented on internal/url/handlers/handlers.go
> +	}
тот же случай про интрейфейс, который описал выше

2022-10-24 13:55 UTC, Perederey commented on internal/url/handlers/handlers_test.go
> +			if assert.NoError(t, postURLJSONHandler.PostURLJSON(c)) {
тут лучше избавиться от табличного теста, так как у тебя от результата выполнения теста зависит его флоу. Нужно обязатлеьно это дело разделять, я бы советовал просто запукать несколько тестов параллейльно.

2022-10-24 13:55 UTC, Perederey commented on internal/url/service/service.go
> +	fileStoragePath := flag.String("f", "", "Input file storage path")
Для того, чтобы парсить флаги и не использовать танцы с указателями, можно использовать flag.StringVar()https://pkg.go.dev/flag#FlagSet.StringVar

2022-10-24 13:55 UTC, Perederey commented on internal/url/storage/storage.go
> +	file, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE, 0777)
1) Каждый раз открывать файл при записи плохо, нужно файл открыть один раз и записывать туда постоянно
2) 0777 - это небезопасно, нужно использовать 0644

2022-10-24 13:55 UTC, Perederey commented on internal/url/storage/storage.go
> +	file, err := os.OpenFile(filename, os.O_RDONLY, 0777)
тоже самое, каждый раз открывать файл не правильно

2022-10-24 15:23 UTC, iRootPro commented on internal/url/handlers/handlers.go
> +	}
на chi переписывать не хочется
А какие еще варианты есть?
1. Использовать глобальную переменную - так себе затея
2. Как сделал я
3. Переделать хендлеры с замыканием и кидать туда cfg

2022-10-27 12:53 UTC, Perederey approved these changes
спасибо, что все поправил)

2022-10-27 12:53 UTC, Perederey commented on cmd/shortener/init.go
> +func InitStorage(cfg *service.ConfigVars) handlers.Storage {
лучше переменовать на New, а StoragePath, сделать как настройку через pattern Options нарпимер

Кстати, из интересного, я смотрю, что тебе может понравиться. Попробуй применить паттерн Options здесь.
https://github.com/Perederey/go_examples/blob/master/options/main.go - вот тут пример, такого паттерна.

2022-10-27 12:53 UTC, Perederey commented on cmd/shortener/main.go
> +  defer fmt.Println("Server shutdown")
```
defer func() {

}
```

и внутри уже все описываешь

2022-10-27 12:53 UTC, Perederey commented on cmd/shortener/main.go
> +	quit := make(chan os.Signal, 1)
сигналов будет больше, но это мы поже еще обсудим)

2022-10-27 12:53 UTC, Perederey commented on internal/url/handlers/handlers_test.go
> +			if assert.NoError(t, serverHandler.PostURLJSON(c)) {
можно вместо if заменить на require.NoError()

2022-10-27 12:53 UTC, Perederey commented on internal/url/storage/storage.go
> +  cache []LinkEntity
возможно StorageFlie может просто содержать в себе StorageMemory?

2022-10-27 15:31 UTC, merged